SOURCE = presentation

make:
	pdflatex $(SOURCE).tex
	pdflatex $(SOURCE).tex

clean: 
	rm -rf $(TARGET) *.class *.html *.log *.aux *.out *.glo *.glg *.gls *.ist *.xdy *.1 *.toc *.snm *.nav *.vrb *.fls *.fdb_latexmk *.pyg
